### ISSUE TITLE
RedirectToAuth and signinArgs mutations in signinSilent

### ISSUE THREAD

**Issue by dankremniov** [thchia/react-oidc#12]
It is just a quick note about the issue I have spotted during the integration of this library in our project. The issue is related to `RedirectToAuth` component.

  In order to replicate the issue you need to have `silent_redirect_uri: true` in your user manager settings and `signinArgs: { data: {} }` (or even just `{}`) in your `makeAuthenticator`.

`RedirectToAuth` tries to do `signinSilent` with `signinArgs` first, however, if it fails (user is not logged in) the catch statement executes `signinRedirect` with the same `signinArgs`. The issue is that most of `oidc-client-js` `UserManager` functions mutate passed args down the line. Hence, the `signArgs` used in catch statement already contain setting which overrides your default settings used during `UserManager` creation and you end up with a redirect to something like https://host:port/silent-callback#error=login_required&state=random_state_id without a chance to login as a result. I managed to solve the issue by using spread operator and creating passing a new object rather than passing a reference to the original one in `signinSilent`:  

```
const user = await this.props.userManager.signinSilent({
    ...this.props.signinArgs
});
```
  Hopefully, it going to save some time for someone or help to improve this package.

**Comment by thchia** [comment]
Hi @Daniellt1, sorry for taking so long to respond to this. Just out of curiosity, do you think the root of this issue is with the fact that the UserManager mutates the args?
