### ISSUE TITLE
Pass props

### ISSUE THREAD

**Issue by chriskolenko** [thchia/react-oidc#14]
https://github.com/thchia/react-oidc/blob/49293dacade4be128438c0b9d388b2b246e986a8/src/makeAuth/index.tsx#L100

Would it be ok to change:
```
<AuthenticatorContext.Provider value={this.state.context}>
  {WrappedComponent}
</AuthenticatorContext.Provider>
```

To:

```
<AuthenticatorContext.Provider value={this.state.context}>
  <WrappedComponent {...this.props} />
</AuthenticatorContext.Provider>
```

**Comment by thchia** [comment]
If I’m not mistaken, looking at the example in the README, this would allow you to pass on props for `AppWithAuth` to the wrapped `App`?

Could you elaborate on the use case? On the one hand you can already pass arbitrary props by specifying them on `<App {...props} />`, but on the other I guess this forces you to do the wrapping at a location where those props are in scope.

**Comment by chriskolenko** [comment]
That's correct. 

I'm using an off the shelf template which requires me to pass in the component directly to the route like such:

```
const AppWithAuth = makeAuthenticator({
  userManager: userManager,
  signinArgs: {
    state: {
      foo: 15
    }
  }
})(<App />);
...
<Route path="/" component={AppWithAuth} />
```

The `<App />` needs some of the props given to it via the Route. IE history + location stuff. 

Passing through the props seems like the best way forward. Just thought I would ask your opinion.

**Comment by thchia** [comment]
@chriskolenko I’m fine in theory with this, but it would be a breaking change since we would no longer pass the rendered App instance anymore, just a reference to the component.

If you want to send a PR I can release it with the appropriate version increase.
