### ISSUE TITLE
Update documentation to version 1.0.0

### ISSUE THREAD

**Issue by amd-9** [thchia/react-oidc#20]
MakeAuthenticator method no longer works after update from 0.3.2 to 1.0.0

Valid code from version 0.3.2

`const authApp = makeAuthenticator(
    {
      userManager,
      placeholderComponent: <h1>Auth Processing.</h1>,
    }
)(<App />);`

now produces error

`Argument of type 'Element' is not assignable to parameter of type 'ComponentType<{}>'.
  Type 'Element' is not assignable to type 'FunctionComponent<{}>'.
    Type 'Element' provides no match for the signature '(props: { children?: ReactNode; }, context?: any): ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any,
any, any>)> | null) | (new (props: any) => Component<...>)> | null'.  TS2345`

Documentation (both Quick Start, Slow start) update is required
`

**Comment by thchia** [comment]
Hmm ok I’ll take a look at this within the next day.

Edit: just to be sure, some things have changed with makeAuthenticator, namely that <App /> should now just be App:

```jsx
makeAuthenticator(...)(App)
```

It’s a breaking change that is documented in the changelog and the readme.
