### ISSUE TITLE
Conditional redirect

### ISSUE THREAD

**Issue by chriskolenko** [thchia/react-oidc#21]
I only want to restrict some routes. Any thoughts or examples on how to do this?

**Comment by thchia** [comment]
Do you mean you only want some routes to be protected by auth? I think rendering them alongside the AppWithAuth should work:

```jsx
<Router>
    <Switch>
      <Route
        path="/callback"
        render={routeProps => (
          <Callback /* omitted for brevity */ />
        )}
      />
      <Route path='/public' ... />
      <AppWithAuth />
    </Switch>
  </Router>
```

**Comment by chriskolenko** [comment]
Oh.. so one could just put all the routes inside `AppWithAuth` that are protected.
