### ISSUE TITLE
signOut function not working as intended

### ISSUE THREAD

**Issue by Ultre00** [thchia/react-oidc#29]
When calling the logOut function from the context I stay logged in. When i check the network tab all i see is a navigation to /connect/authorize. When I use the userManager from the context and i call. userManager.SignOutRedirect everything is working as intended. Then indeed the /connect/endsession endpoint is called. Am i missing something here ?

this is my config:
```javascript 
const config = {
  authority: 'https://localhost:44347',
  client_id: 'react_app',
  redirect_uri: 'http://localhost:3000/callback',
  post_logout_redirect_uri: 'http://localhost:3000',
  response_type: 'code',
  scope: 'openid profile api',
};
```
The component calling the signout:
```javascript
import React, { useContext } from 'react';
import './Header.scss';
import { UserData } from 'react-oidc';
import FAIcon from './FAIcon';

const Header = () => {
  const { signOut, user: { profile: { preferred_username: userName } } } = useContext(UserData);
  return (
    <div className='r2r-header'>
      <div className='flex-right'>
        {userName}
        {' '}
        <FAIcon onClick={signOut} className='r2r-header-icon-button' icon='sign-out-alt' />
      </div>
    </div>
  );
};
export default Header;
```
When I swap the signOut with the userManager.SignoutRedirect it does work

**Comment by thchia** [comment]
Yeah I think the signoutRedirect call is missing from the exposed logout function.
