### ISSUE TITLE
Unable to set State

### ISSUE THREAD

**Issue by FizzBuzz791** [thchia/react-oidc#9]
In this line;
https://github.com/thchia/react-oidc/blob/3cc8e4fdcad520016eb50318a7f5b406bd312524/src/RedirectToAuth/index.tsx#L18

`signinRedirect()` takes `args` which are eventually used like this;
https://github.com/IdentityModel/oidc-client-js/blob/dev/samples/VanillaJS/public/oidc-client-sample.js#L37

State is a valuable resource, so it'd be great if this library could pass that through.

**Comment by thchia** [comment]
@FizzBuzz791 thanks for highlighting this.

Is this state something that can be passed to `makeAuthenticator()`, alongside the `userManager` instance? I'm not clear exactly how the state can be used, so I'm not sure how "dynamic" it needs to be.

If it is static, then I don't foresee any issues with declaring it in `makeAuthenticator`:

```jsx
const AppWithAuth = makeAuthenticator({
  userManager: userManagerInstance,
  state: { foo: 15 }
})
```

**Comment by FizzBuzz791** [comment]
Ah, not quite. State is a pass-through that is echoed back in the response;
https://auth0.com/docs/protocols/oauth2/oauth-state

It can be used for things such as maintaining query parameters and anything that might be transient.

I'm working through modifying a copy of this library in my project in order to get it passed through and it probably can be passed to the makeAuthenticator call (as a side note, I'd like to look at why this is a function and not a component, but that's another issue for another time). Happy to put up a PR when it's done.

**Comment by thchia** [comment]
@FizzBuzz791 great!

I've been looking more closely at the `oidc-client-js` source code, and I can't figure out where the state is returned _from_ the Identity Provider (this doesn't affect using state for things like redirecting the user back to the route they were trying to access).

I understand one use of state is to mitigate CSRF attacks as mentioned in the auth0 document, but this requires comparing some arbitrary state value that was passed with the one that was returned. I assumed it would be returned through the `signinRedirectCallback` call, but AFAICT this only passes back the user object.

**Comment by FizzBuzz791** [comment]
Yeah, so the handling is here-ish;
https://github.com/IdentityModel/oidc-client-js/blob/01c872abc145114c76d9491b242d4d814c07e22a/src/UserManager.js#L333-L347

Basically, state ends up being part of the user object and I *think* there might actually be an issue with state not getting stored, which kind of compounds the issue (there are ways around it though, so it's not a show-stopper); https://github.com/IdentityModel/oidc-client-js/issues/730

The reason I need state is because of some extreme security measures that mean that I can't have wildcards on my redirect, so I can't just append the input query params to the redirect url that is passed to oidc. I imagine most use-cases don't have the issue I'm having.
